In [ ]:
import os
from skimage.io import imread
from skimage.transform import resize
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from keras.models import Sequential

In [ ]:
train_path='/content/drive/MyDrive/CNN_project_dataset_sitting_posture/Training'
categories=['Bad_Posture','Good_Posture']
X_train=[]
y_train=[]
for category in categories:
  fold_path=os.path.join(train_path,category)
  #print(fold_path)
  images=os.listdir(fold_path)
  #print(images)
  for img in images:
    img_path=os.path.join(fold_path,img)
    #print(img_path)
    img_array=imread(img_path)
    img=resize(img_array,(150,150,1))
    X_train.append(img)
    y_train.append(categories.index(category))
  print("Loaded Category",category)

Loaded Category Bad_Posture
Loaded Category Good_Posture


In [ ]:
test_path='/content/drive/MyDrive/CNN_project_dataset_sitting_posture/Testing'
categories=['Bad_Posture','Good_Posture']
X_test=[]
y_test=[]
for category in categories:
  fold_path1=os.path.join(test_path,category)
  images1=os.listdir(fold_path1)
  for img1 in images1:
    img_path1=os.path.join(fold_path1,img1)
    img_array1=imread(img_path1)
    img1=resize(img_array1,(150,150,1))
    X_test.append(img1)
    y_test.append(categories.index(category))
  print("Loaded Category",category)

Loaded Category Bad_Posture
Loaded Category Good_Posture


In [ ]:
import numpy as np
X_train=np.array(X_train)
y_train=np.array(y_train)

In [ ]:
X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
X_train.shape,y_train.shape

((573, 150, 150, 1), (573,))

In [ ]:
X_test.shape,y_test.shape

((27, 150, 150, 1), (27,))

In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(2,activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=20,batch_size=16)

Epoch 1/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - accuracy: 0.5119 - loss: 0.9554
Epoch 2/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6620 - loss: 0.5529
Epoch 3/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9056 - loss: 0.2256
Epoch 4/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9934 - loss: 0.0413
Epoch 5/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9941 - loss: 0.0266
Epoch 6/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9988 - loss: 0.0108
Epoch 7/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0021
Epoch 8/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 9/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 10/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 1.0000 - loss: 7.6660e-04
Epoch 11/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 6.1159e-04
Epoch 12/20
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy:

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 148, 148, 32)        │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 74, 74, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 72, 72, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 36, 36, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 41472)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 100)                 │       4,147,300 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │             202 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 12,471,212 (47.57 MB)

 Trainable params: 4,157,070 (15.86 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 8,314,142 (31.72 MB)

In [ ]:
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 702ms/step - accuracy: 0.9259 - loss: 0.2822


[0.282204270362854, 0.9259259104728699]

In [ ]:
y_pred=model.predict(X_test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step


array([[9.9999988e-01, 6.7822192e-08],
       [1.0000000e+00, 4.4999279e-10],
       [1.0000000e+00, 9.1048835e-11],
       [1.0000000e+00, 4.6939359e-09],
       [1.0000000e+00, 2.5433736e-10],
       [9.9998891e-01, 1.1050804e-05],
       [9.9999940e-01, 5.9086506e-07],
       [1.0000000e+00, 6.9804940e-10],
       [9.9999809e-01, 1.8702191e-06],
       [9.9998188e-01, 1.8100882e-05],
       [9.9982357e-01, 1.7636819e-04],
       [2.0989487e-02, 9.7901058e-01],
       [7.5277859e-01, 2.4722141e-01],
       [9.9987340e-01, 1.2659028e-04],
       [7.1526885e-02, 9.2847311e-01],
       [9.9999940e-01, 5.4543199e-07],
       [9.9999964e-01, 3.0642136e-07],
       [2.1877579e-01, 7.8122419e-01],
       [1.0266154e-03, 9.9897337e-01],
       [4.4138822e-01, 5.5861175e-01],
       [2.5421685e-05, 9.9997461e-01],
       [2.3611283e-03, 9.9763894e-01],
       [2.6388236e-06, 9.9999738e-01],
       [2.2421944e-05, 9.9997759e-01],
       [1.8302404e-06, 9.9999821e-01],
       [1.1234350e-03, 9.

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [ ]:
y_pred1=y_pred.argmax(axis=1)
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.83      1.00      0.91        10

    accuracy                           0.93        27
   macro avg       0.92      0.94      0.92        27
weighted avg       0.94      0.93      0.93        27



In [ ]:
def predict_new(img,model):
  img_resized=resize(img,(150,150,1))
  img_reshaped=img_resized.reshape(1,150,150,1)
  pred=model.predict(img_reshaped)
  ind=pred.argmax()
  categories=['Bad_Posture','Good_Posture']
  print(categories[ind])

In [ ]:
imgpath=input("Enter the image path")
img=imread(imgpath)
predict_new(img,model)

Enter the image path/content/drive/MyDrive/CNN_project_dataset_sitting_posture/Valid/bad_posture_20241007_192301_jpg.rf.fa66c9b3bc5dce6eddbcd80cff3b46ab.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Good_Posture


In [ ]:
from tensorflow.keras.models import load_model

# Save model
model.save('my_model.h5')